import { HealthMilestone } from '@/types/smoking';

export const healthMilestones: Omit<HealthMilestone, 'achieved' | 'progress'>[] = [
  // Minutes to hours
  {
    id: '20min',
    title: 'Heart Rate Normalizes',
    description: 'Your heart rate and blood pressure begin to drop to normal levels.',
    timeInHours: 0.33,
    icon: '❤️',
  },
  {
    id: '1hour',
    title: 'Blood Pressure Drops',
    description: 'Your blood pressure is starting to return to healthier levels.',
    timeInHours: 1,
    icon: '📉',
  },
  {
    id: '2hours',
    title: 'Nicotine Cravings Begin',
    description: 'You may feel the first cravings. Stay strong - they peak and pass!',
    timeInHours: 2,
    icon: '💪',
  },
  {
    id: '4hours',
    title: 'Blood Sugar Stabilizes',
    description: 'Your blood sugar levels are normalizing without nicotine stimulation.',
    timeInHours: 4,
    icon: '🩸',
  },
  {
    id: '6hours',
    title: 'Heart Rate Steady',
    description: 'Your heart rate has been stable for hours. Great progress!',
    timeInHours: 6,
    icon: '💓',
  },
  {
    id: '8hours',
    title: 'Oxygen Levels Rise',
    description: 'Carbon monoxide levels in your blood drop, oxygen levels increase.',
    timeInHours: 8,
    icon: '🫁',
  },
  {
    id: '10hours',
    title: 'Oxygen Delivery Improving',
    description: 'Your blood is carrying more oxygen to your organs and muscles.',
    timeInHours: 10,
    icon: '🔴',
  },
  {
    id: '12hours',
    title: 'Carbon Monoxide Cleared',
    description: 'Carbon monoxide levels return to normal, improving oxygen delivery.',
    timeInHours: 12,
    icon: '🌬️',
  },
  {
    id: '16hours',
    title: 'Detox In Progress',
    description: 'Your body is actively flushing out toxins from cigarettes.',
    timeInHours: 16,
    icon: '🧹',
  },
  {
    id: '20hours',
    title: 'Almost One Day!',
    description: 'You\'re approaching a full day smoke-free. Incredible willpower!',
    timeInHours: 20,
    icon: '⏰',
  },
  // Day milestones
  {
    id: '24hours',
    title: 'First Full Day!',
    description: 'Your risk of heart attack begins to decrease significantly.',
    timeInHours: 24,
    icon: '🫀',
  },
  {
    id: '30hours',
    title: 'Anxiety Peaks',
    description: 'Withdrawal anxiety may peak now. Remember: this too shall pass.',
    timeInHours: 30,
    icon: '🧘',
  },
  {
    id: '36hours',
    title: 'Sense of Smell Returns',
    description: 'Your sense of smell and taste start to improve noticeably.',
    timeInHours: 36,
    icon: '👃',
  },
  {
    id: '42hours',
    title: 'Nerve Regeneration Starts',
    description: 'Damaged nerve endings are beginning to regrow.',
    timeInHours: 42,
    icon: '⚡',
  },
  {
    id: '48hours',
    title: 'Nicotine Free!',
    description: 'All nicotine has left your body. Nerve endings start regenerating.',
    timeInHours: 48,
    icon: '✨',
  },
  {
    id: '60hours',
    title: 'Taste Buds Awakening',
    description: 'Food starts tasting much better as your taste buds recover.',
    timeInHours: 60,
    icon: '👅',
  },
  {
    id: '72hours',
    title: 'Breathing Easier',
    description: 'Bronchial tubes relax, breathing becomes easier, energy increases.',
    timeInHours: 72,
    icon: '🌈',
  },
  {
    id: '4days',
    title: 'Physical Symptoms Peak',
    description: 'The worst physical symptoms are usually over. You\'re so strong!',
    timeInHours: 96,
    icon: '🏔️',
  },
  {
    id: '5days',
    title: 'Cravings Reduce',
    description: 'Most nicotine cravings last only 3-5 minutes. You\'re getting stronger!',
    timeInHours: 120,
    icon: '🎯',
  },
  {
    id: '6days',
    title: 'Sleep Improving',
    description: 'Your sleep patterns are starting to normalize.',
    timeInHours: 144,
    icon: '😴',
  },
  // Week milestones
  {
    id: '1week',
    title: 'One Week Strong!',
    description: 'You\'ve made it a full week! The hardest part is behind you.',
    timeInHours: 168,
    icon: '🌟',
  },
  {
    id: '10days',
    title: 'Circulation Improving',
    description: 'Blood flow to your gums and teeth is now similar to a non-smoker.',
    timeInHours: 240,
    icon: '😁',
  },
  {
    id: '2weeks',
    title: 'Two Weeks Champion',
    description: 'Your circulation has significantly improved, walking becomes easier.',
    timeInHours: 336,
    icon: '🚶',
  },
  {
    id: '17days',
    title: 'Energy Surge',
    description: 'Many people report a significant increase in energy around this time.',
    timeInHours: 408,
    icon: '⚡',
  },
  {
    id: '3weeks',
    title: 'Withdrawal Fading',
    description: 'Physical withdrawal symptoms are mostly gone. Mental habits remain.',
    timeInHours: 504,
    icon: '🧘',
  },
  {
    id: '25days',
    title: 'Skin Renewal Starting',
    description: 'Your skin is starting to look healthier and more vibrant.',
    timeInHours: 600,
    icon: '🌸',
  },
  // Month milestones
  {
    id: '1month',
    title: 'One Month Warrior!',
    description: 'Lung function increases up to 30%. Coughing and shortness of breath decrease.',
    timeInHours: 720,
    icon: '🏃',
  },
  {
    id: '5weeks',
    title: 'Cough Clearing',
    description: 'Smoker\'s cough is significantly reduced or gone completely.',
    timeInHours: 840,
    icon: '🗣️',
  },
  {
    id: '6weeks',
    title: 'Skin Glowing',
    description: 'Your skin is clearer and more hydrated. The "smoker\'s complexion" fades.',
    timeInHours: 1008,
    icon: '✨',
  },
  {
    id: '7weeks',
    title: 'Immunity Boosting',
    description: 'Your immune system is getting stronger every day.',
    timeInHours: 1176,
    icon: '🛡️',
  },
  {
    id: '2months',
    title: 'Two Months Hero!',
    description: 'The cilia in your lungs are regrowing, helping clear mucus and debris.',
    timeInHours: 1440,
    icon: '🌱',
  },
  {
    id: '10weeks',
    title: 'Blood Flow Optimized',
    description: 'Circulation to your hands and feet has greatly improved.',
    timeInHours: 1680,
    icon: '🩸',
  },
  {
    id: '3months',
    title: 'Quarter Year Victory!',
    description: 'The cilia in your lungs have regrown, reducing risk of infection.',
    timeInHours: 2160,
    icon: '🏆',
  },
  {
    id: '4months',
    title: 'Exercise Easier',
    description: 'Physical activities feel easier. Your body is healing rapidly.',
    timeInHours: 2880,
    icon: '🏋️',
  },
  {
    id: '5months',
    title: 'Mental Clarity',
    description: 'Brain fog is clearing. Concentration and memory are improving.',
    timeInHours: 3600,
    icon: '🧠',
  },
  {
    id: '6months',
    title: 'Half Year Legend!',
    description: 'Your body\'s stress response has normalized without nicotine.',
    timeInHours: 4320,
    icon: '😌',
  },
  {
    id: '7months',
    title: 'Mood Stabilized',
    description: 'Anxiety and depression from quitting have largely subsided.',
    timeInHours: 5040,
    icon: '😊',
  },
  {
    id: '8months',
    title: 'Dental Health Improved',
    description: 'Your gums and teeth are much healthier. Staining is fading.',
    timeInHours: 5760,
    icon: '🦷',
  },
  {
    id: '9months',
    title: 'Lungs Significantly Healed',
    description: 'Lung cilia fully recovered. Infections, colds, and breathing issues decrease.',
    timeInHours: 6480,
    icon: '💨',
  },
  {
    id: '10months',
    title: 'Energy Peak',
    description: 'Your energy levels are now consistently higher than when you smoked.',
    timeInHours: 7200,
    icon: '🚀',
  },
  {
    id: '11months',
    title: 'Almost One Year!',
    description: 'You\'re approaching an incredible milestone. So proud of you!',
    timeInHours: 7920,
    icon: '🎊',
  },
  // Year milestones
  {
    id: '1year',
    title: 'One Year Champion!',
    description: 'Your excess risk of coronary heart disease is now half that of a smoker.',
    timeInHours: 8760,
    icon: '🎉',
  },
  {
    id: '15months',
    title: 'Sustained Victory',
    description: 'You\'ve proven you can live smoke-free long-term. Amazing!',
    timeInHours: 10950,
    icon: '💎',
  },
  {
    id: '18months',
    title: 'Lung Cancer Risk Dropping',
    description: 'Your risk of lung cancer is starting to decrease significantly.',
    timeInHours: 13140,
    icon: '📉',
  },
  {
    id: '2years',
    title: 'Two Years Free!',
    description: 'Your risk of stroke has dramatically decreased.',
    timeInHours: 17520,
    icon: '🧠',
  },
  {
    id: '3years',
    title: 'Three Years Strong!',
    description: 'Your risk of heart attack is now similar to someone who never smoked.',
    timeInHours: 26280,
    icon: '❤️‍🩹',
  },
  {
    id: '4years',
    title: 'Four Years Warrior!',
    description: 'Oral cancer risk has dropped significantly.',
    timeInHours: 35040,
    icon: '👄',
  },
  {
    id: '5years',
    title: 'Five Years Legend!',
    description: 'Your risk of stroke is now the same as a non-smoker.',
    timeInHours: 43800,
    icon: '🌟',
  },
  {
    id: '7years',
    title: 'Seven Years Hero!',
    description: 'Your risk of type 2 diabetes is the same as a non-smoker.',
    timeInHours: 61320,
    icon: '🩺',
  },
  {
    id: '10years',
    title: 'Decade Champion!',
    description: 'Your risk of dying from lung cancer is about half that of a smoker.',
    timeInHours: 87600,
    icon: '🏆',
  },
  {
    id: '13years',
    title: 'Tooth Loss Risk Normal',
    description: 'Your risk of losing teeth is now the same as a non-smoker.',
    timeInHours: 113880,
    icon: '😁',
  },
  {
    id: '15years',
    title: 'Heart Disease Risk Normal',
    description: 'Your risk of heart disease is now equal to a non-smoker.',
    timeInHours: 131400,
    icon: '💖',
  },
  {
    id: '20years',
    title: 'Two Decades Free!',
    description: 'Your risk of death from smoking-related causes is similar to a non-smoker.',
    timeInHours: 175200,
    icon: '👑',
  },
  {
    id: '25years',
    title: 'Quarter Century!',
    description: 'You\'ve lived 25 years smoke-free. An inspiration to everyone!',
    timeInHours: 219000,
    icon: '🌈',
  },
];

export function calculateMilestones(hoursSinceQuit: number): HealthMilestone[] {
  return healthMilestones.map((milestone) => ({
    ...milestone,
    achieved: hoursSinceQuit >= milestone.timeInHours,
    progress: Math.min(100, (hoursSinceQuit / milestone.timeInHours) * 100),
  }));
}

export function getCurrentAndNextMilestone(hoursSinceQuit: number) {
  const milestones = calculateMilestones(hoursSinceQuit);
  const achieved = milestones.filter((m) => m.achieved);
  const upcoming = milestones.filter((m) => !m.achieved);

  return {
    current: achieved[achieved.length - 1] || null,
    next: upcoming[0] || null,
  };
}

// Health improvement data for charts (percentage of recovery)
export const healthRecoveryData = [
  { time: '20min', heartRate: 100, oxygen: 10, lungFunction: 0, circulation: 5 },
  { time: '8hr', heartRate: 100, oxygen: 50, lungFunction: 0, circulation: 10 },
  { time: '24hr', heartRate: 100, oxygen: 100, lungFunction: 5, circulation: 15 },
  { time: '48hr', heartRate: 100, oxygen: 100, lungFunction: 10, circulation: 20 },
  { time: '72hr', heartRate: 100, oxygen: 100, lungFunction: 15, circulation: 25 },
  { time: '1wk', heartRate: 100, oxygen: 100, lungFunction: 20, circulation: 35 },
  { time: '2wk', heartRate: 100, oxygen: 100, lungFunction: 25, circulation: 50 },
  { time: '1mo', heartRate: 100, oxygen: 100, lungFunction: 30, circulation: 60 },
  { time: '3mo', heartRate: 100, oxygen: 100, lungFunction: 50, circulation: 75 },
  { time: '6mo', heartRate: 100, oxygen: 100, lungFunction: 65, circulation: 85 },
  { time: '9mo', heartRate: 100, oxygen: 100, lungFunction: 80, circulation: 90 },
  { time: '1yr', heartRate: 100, oxygen: 100, lungFunction: 90, circulation: 95 },
  { time: '5yr', heartRate: 100, oxygen: 100, lungFunction: 95, circulation: 100 },
  { time: '10yr', heartRate: 100, oxygen: 100, lungFunction: 100, circulation: 100 },
];
